# Generated by Django 5.1.2 on 2024-11-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_orderitem_order_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='productos',
        ),
    ]
